### ISSUE TITLE
Warning: Use Cipheriv for counter mode of aes-256-ctr

### ISSUE THREAD

**Issue by doormalena** [jabbera/vsts-authenticode#28]
I noticed the following warning being present in our build pipeline. 

> (node:4840) Warning: Use Cipheriv for counter mode of aes-256-ctr

We're using YAML and our configuration is like this:
```yml
steps:
  - task: jabbera.authenticode-sign.authenticode-sign.authenticode-sign@4
    displayName: "Code sign"
    inputs:
      filePath: |
        **/*.@${{ parameters.extensionsToSign }}
      signRootPath: "${{ parameters.rootDirectory }}"
      timestampServer: "${{ parameters.timeStamper }}"
      timestampServerDelay: 0
      certificateLocation: pfxFile
      pfxFile: "${{ parameters.certificateFilePath }}"
      pfxPassword: "${{ parameters.certificatePassword }}"
      additionalArguments: |
        /debug
        /v
```

This results in the following output in Azure DevOps:
![image](https://user-images.githubusercontent.com/8328876/74453460-b9e92200-4e82-11ea-847b-13a2e277c947.png)
